const storyText =
    `Once upon a time, there was a user browsing through a CV online. As they scrolled through the document, their attention was caught by the logo. Without hesitation, they clicked on it, curious to see what would happen.
To their surprise, a new window opened up, revealing a story generated by an AI language model. As they read through the story, the user couldn't help but feel a strange sense of familiarity. It was as if the tale was about them, and their actions were being narrated in real-time.
The story described how the user had clicked the logo, seeking out new knowledge and experiences. It spoke of their insatiable curiosity and desire to explore the unknown. The user couldn't believe what they were reading - it was as if the AI language model had somehow captured their essence in a story.
As the story came to an end, the user was left with a deep sense of introspection. They realized that their actions had been noticed, even in the virtual world. It was a humbling reminder that every action they took had the potential to make a difference, no matter how small.
With a renewed sense of purpose, the user closed the window and continued their browsing. They knew that they would never forget this moment - the moment when they saw themselves reflected in a story generated by an AI language model.
`.split("\n");

export const story = (
    <>
        {storyText.map((line) => (
            <p>{line}</p>
        ))}
    </>
);
